server:
  port: 8000

spring:
  application:
    name: cambio-service
  datasource:
      url: jdbc:mysql://localhost:3306/cambio_service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: root
    password: root